apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sky-dev
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/chizchig/trivy.git
    targetRevision: HEAD
    path: resource/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-namespace
  syncPolicy:
    automated:
      selfHeal: true 
      prune: true