apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-deployment
  namespace: argocd
  labels:
    app: skye-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skye-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: skye-app
    spec:
      serviceAccountName: sky-service-account
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: sky
          image: shadowhub/cocomaster:20240506044802
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
              readOnly: true  # Changed to readOnly to address Volume Mount issue
          securityContext:
            allowPrivilegeEscalation: false  # Added to address Privilege Escalation
            runAsNonRoot: true  # Added to enforce non-root execution
          resources:
            limits:
              cpu: "10m"
              memory: "1Gi"
            requests:
              cpu: "10m"  # Equal to limits to address Container Requests Not Equal
              memory: "1Gi"  # Equal to limits to address Container Requests Not Equal
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-storage
          emptyDir: {}