apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-deployment
  namespace: argocd
  labels:
    app: skye-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skye-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 4
  template:
    metadata:
      labels:
        app: skye-app
    spec:
      serviceAccountName: sky-service-account
      imagePullSecrets:
        - name: sky-access-token
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: sky
          image: shadowhub/cocomaster
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
              readOnly: false
          resources:
            limits:
              cpu: "10m"
              memory: "1Gi"
            requests:
              cpu: "10m"
              memory: "512Mi"
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-storage
          emptyDir: {}