apiVersion: v1
kind: Service
metadata:
  managedFields:
  name: sky-service
  namespace: argocd
  labels:
    app: skye-app
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: skye-app