apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

patches:
  - |
  
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sky-deployment
      namespace: argocd
    spec:
      replicas: 4