name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write
  id-token: write
  actions: read
  contents: read

jobs:
  security_scan:
    name: Trivy Vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Verify System Architecture'
      run: |
        uname -a
        arch

    - name: 'Install Docker'
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64]https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'my-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        scanners: 'vuln'
    - name: 'Install Minikube'
      run: |
        curl Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minnikube /usr/local/bin/

    - name: 'Start Minikube'
      run: |
       minikube start --driver=docker

    - name: 'Set up Kubeconfig for Minikube'
      run: |
        mkdir -p $HOME/.kube
        minikube update-context

    - name: 'Verify Kubernetes Context'
      run: Kubectl config current-context