name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  security-events: write
  id-token: write
  actions: read
  contents: read

jobs:
  security_scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify System Architecture
      run: |
        uname -a
        arch

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Pull Docker Image
      run: |
        docker pull shadowhub/cocomaster:20240506044802

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'shadowhub/cocomaster:20240506044802'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        scanners: 'vuln'

    - name: Upload Trivy Results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif

    - name: Run KICS IaC Scan
      uses: checkmarx/kics-action@v1
      with:
        path: deployments/sky-deployment.yaml
        output_path: kics-results.json
        format: json

    - name: Upload KICS Results
      uses: actions/upload-artifact@v4
      with:
        name: kics-results
        path: kics-results.json

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set up Kubeconfig for Minikube
      run: |
        mkdir -p $HOME/.kube
        minikube update-context

    - name: Verify Kubernetes Context
      run: |
        kubectl config current-context

    - name: Create ArgoCD Namespace
      run: |
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

    - name: Create Service Account
      run: |
        kubectl create serviceaccount sky-service-account -n argocd --dry-run=client -o yaml | kubectl apply -f -

    - name: Create Image Pull Secret in Minikube
      run: |
        # Optional: Remove this step if not needed for a public image
        kubectl create secret docker-registry sky-access-token \
          --docker-username=${{ secrets.DOCKER_USERNAME }} \
          --docker-password=${{ secrets.DOCKER_PASSWORD }} \
          --docker-server=https://index.docker.io/v1/ \
          -n argocd --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployments/sky-deployment.yaml