name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  security-events: write
  id-token: write
  actions: read
  contents: read

jobs:
  security_scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify System Architecture
      run: |
        uname -a
        arch

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        # Download and add Docker's GPG key to trusted.gpg.d
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
        # Add Docker repository with proper spacing
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: 'my-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        scanners: 'vuln'

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set up Kubeconfig for Minikube
      run: |
        mkdir -p $HOME/.kube
        minikube update-context

    - name: Verify Kubernetes Context
      run: |
        kubectl config current-context